<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FiltroSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('filtros')->truncate();

DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'MARIA MARLEN SUAREZ RODRIGUEZ','cedula'=>'1090503894','telefono'=>'3007495834','correo'=>'FGUTIERREZ0012@GMAIL.COM','perfil'=>'Analista de bases','campaña'=>'ETB','fuente'=>'Vincuventas','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'WALDER ROA CORRAL','cedula'=>'1003163721','telefono'=>'3003250773','correo'=>'PAO_RU15@HOTMAIL.COM','perfil'=>'Analista de Calidad','campaña'=>'Movistar','fuente'=>'Computrabajo','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'MIGUEL ANGEL GIL VALENCIA','cedula'=>'98632688','telefono'=>'3017512997','correo'=>'INGJULIANMORALES@GMAIL.COM','perfil'=>'Analista de Contratacion','campaña'=>'QNT','fuente'=>'SNE','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'NAZLY MARGARITA TOBAR VAZQUEZ','cedula'=>'1235045853','telefono'=>'3214355077','correo'=>'HUGOMARIOHURTADO@HOTMAIL.COM','perfil'=>'Analista de nomina','campaña'=>'Staff Mentius','fuente'=>'Compensar','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'ALIX LUCIA ORTIZ LOPEZ','cedula'=>'1022402678','telefono'=>'3023888812','correo'=>'LUDISE77@HOTMAIL.COM','perfil'=>'Analista de Reclutamiento y Seleccion','campaña'=>'Vanti','fuente'=>'rt','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'ADRIANA MERCHAN ACEVEDO','cedula'=>'1075317066','telefono'=>'3134391062','correo'=>'KAROLDAYANA30@GMAIL.COM','perfil'=>'Analista IT','campaña'=>'Vanti S A C','fuente'=>'rj','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'JUAN FERNANDO GIL','cedula'=>'45520570','telefono'=>'3505172933','correo'=>'THAROL630114@GMAIL.COM','perfil'=>'Aprendiz Sena','campaña'=>'ETB','fuente'=>'rc','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'NESTOR FABIAN SANCHEZ MALPICA','cedula'=>'1090495367','telefono'=>'3126944354','correo'=>'juandtamayo3091@gmail.com','perfil'=>'Asesor Comercial','campaña'=>'Movistar','fuente'=>'univ','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'GLORIA ROSA ANGARITA CARRASCAL','cedula'=>'28756239','telefono'=>'3004351477','correo'=>'oscargustavonovoarojas@gmail.com','perfil'=>'Asesor de Cartera','campaña'=>'QNT','fuente'=>'redes','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'INGRITH VANESA GOMEZ MARTINEZ','cedula'=>'1115077284','telefono'=>'3006170191','correo'=>'ARQJOSELUIS84@GMAIL.COM','perfil'=>'Asesor de Servicio al Cliente','campaña'=>'Staff Mentius','fuente'=>'hv','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'LADY CAROLINA GARCIA BARRERO','cedula'=>'1065627181','telefono'=>'3053635014','correo'=>'katiaccastillo01@gmail.com','perfil'=>'Asistente Contable','campaña'=>'Vanti','fuente'=>'funda','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'YERLIS ALEGRE MESTRA','cedula'=>'36697579','telefono'=>'3105771014','correo'=>'juansernahoyos@gmail.com','perfil'=>'Auxiliar administrativo','campaña'=>'Vanti S A C','fuente'=>'Vincuventas','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'YAMILE MARTINEZ','cedula'=>'10012108','telefono'=>'3188464800','correo'=>'ROC.KHAN@HOTMAIL.COM','perfil'=>'Auxiliar contable','campaña'=>'ETB','fuente'=>'Computrabajo','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'ANDREW STEWENS CASTELLANOS OVALLE','cedula'=>'23011013','telefono'=>'3158367050','correo'=>'SARAI380@HOTMAIL.COM','perfil'=>'Auxiliar IT','campaña'=>'Movistar','fuente'=>'SNE','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'LIZETH NATALY PRIETO BUITRAGO','cedula'=>'1067925643','telefono'=>'3108584436','correo'=>'ELIMADRIDRANGEL@GMAIL.COM','perfil'=>'Auxiliar SST','campaña'=>'QNT','fuente'=>'Compensar','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'FLOR ERMINDA VELANDIA NOVOA','cedula'=>'1120365405','telefono'=>'3046337312','correo'=>'MILEISY@GHOTMAIL.COM','perfil'=>'Backoffice','campaña'=>'Staff Mentius','fuente'=>'rt','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'SOL MARIA MANOTAS PALMA','cedula'=>'31176158','telefono'=>'3004919335','correo'=>'ESTEBAN27.28@OUTLOOK.ES','perfil'=>'Coord. Administrativo','campaña'=>'Vanti','fuente'=>'rj','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'JORGE EMIRO ZAMORA ACEVEDO','cedula'=>'52966866','telefono'=>'3104497477','correo'=>'LORENABLANQUICETT@GMAIL.COM','perfil'=>'Coordinador administrativo','campaña'=>'Vanti S A C','fuente'=>'rc','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'MARBELI JUDITH GARCIA','cedula'=>'1005297258','telefono'=>'3206917607','correo'=>'villajhon36@gmail.com','perfil'=>'Coordinador de Operacion','campaña'=>'ETB','fuente'=>'univ','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'MAYRA ISABEL MEZA LIZARAZO','cedula'=>'51811234','telefono'=>'3117797954','correo'=>'rafaelsuarezdt@gmail.com','perfil'=>'Coordinador de operaciones','campaña'=>'Movistar','fuente'=>'redes','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'JHONY LEANDRO GUTIERREZ MARTINEZ','cedula'=>'14650182','telefono'=>'3242169680','correo'=>'luisortizzz.1904@gmail.com','perfil'=>'Datamarshall Junior','campaña'=>'QNT','fuente'=>'hv','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'OSCAR EDUARDO MOURAD SAUMETH','cedula'=>'1006772209','telefono'=>'3015545236','correo'=>'hectorserna94@gmail.com','perfil'=>'Datamarshall Senior','campaña'=>'Staff Mentius','fuente'=>'funda','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'NEILYN MARICELL ROJAS GARCIA','cedula'=>'80471480','telefono'=>'3142675830','correo'=>'lvriosv@gmail.com','perfil'=>'Director de operaciones','campaña'=>'Vanti','fuente'=>'Vincuventas','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'JUAN PABLO LATORRE BERNAL','cedula'=>'1045738940','telefono'=>'3155771123','correo'=>'DIEGOALEJANDROJOSE@GMAIL.COM','perfil'=>'Director financiero','campaña'=>'Vanti S A C','fuente'=>'Computrabajo','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'ROBERTO EDUARDO GOMEZ ORDUZ GONZALEZ','cedula'=>'1065867114','telefono'=>'3104263857','correo'=>'jarolandreschacon@gmail.com','perfil'=>'Director IT','campaña'=>'ETB','fuente'=>'SNE','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'ANTONIO MARIA BOLAÑO PATERNINA','cedula'=>'1018410341','telefono'=>'3103412332','correo'=>'angelamatilde06@gmail.com','perfil'=>'Director RRHH','campaña'=>'Movistar','fuente'=>'Compensar','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'LUIS RAMON RODRIGUEZ ROLON RODRIGUEZ ROLON','cedula'=>'1128280017','telefono'=>'3157406646','correo'=>'mfduartes95@gmail.com','perfil'=>'Formador junior','campaña'=>'QNT','fuente'=>'rt','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'CARLOS ARMANDO RIVER MESA','cedula'=>'1233695565','telefono'=>'3167734833','correo'=>'ninijesus.8@gmail.com','perfil'=>'Formador senior','campaña'=>'Staff Mentius','fuente'=>'rj','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'JORGE LEONARDO VELASQUEZ GONZALEZ','cedula'=>'80811397','telefono'=>'3148331556','correo'=>'luisacuadro25@gmail.com','perfil'=>'Gerencia Administrativa','campaña'=>'Vanti','fuente'=>'rc','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'LUIS CARLOS GARCIA RADA','cedula'=>'76324235','telefono'=>'3017907738','correo'=>'DAIROGIM@GMAIL.COM','perfil'=>'Gerencia Comercial','campaña'=>'Vanti S A C','fuente'=>'univ','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'SANTIAGO RESTREPO LOPEZ','cedula'=>'1028014491','telefono'=>'3125728151','correo'=>'andaduran727@gmail.com','perfil'=>'Gerencia General','campaña'=>'ETB','fuente'=>'redes','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'WILSON OSWALDO CASTRO','cedula'=>'1013659874','telefono'=>'3014790185','correo'=>'jotajotagp21@gmail.com','perfil'=>'Gerente comercial','campaña'=>'Movistar','fuente'=>'hv','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'ASTRID MARCELA SANTANA GARCIA','cedula'=>'1019059117','telefono'=>'3112347743','correo'=>'XILENAREYES@GMAIL.COM','perfil'=>'Gerente financiero','campaña'=>'QNT','fuente'=>'funda','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'angie marcela ospina cuesta','cedula'=>'1018496130','telefono'=>'3133848815','correo'=>'MACHADOALEX72@GMAIL.COM','perfil'=>'Gerente general','campaña'=>'Staff Mentius','fuente'=>'Vincuventas','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'JESSICA PAOLA HOYOS LUQUE','cedula'=>'1013593447','telefono'=>'3041560628','correo'=>'MACHADOALEX72@GMAIL.COM','perfil'=>'Gestor documental','campaña'=>'ETB','fuente'=>'Computrabajo','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'JENNY PAOLA HERNDEZ FAJARDO','cedula'=>'1048274522','telefono'=>'3196806691','correo'=>'andreita-201180@hotmail.com','perfil'=>'Jefe de operaciones','campaña'=>'Movistar','fuente'=>'SNE','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'KELLY DAYANA HERNANDEZ ORDUS','cedula'=>'43163632','telefono'=>'3134911348','correo'=>'alvarolaverde@gmail.com','perfil'=>'Lider Backoffice','campaña'=>'QNT','fuente'=>'Compensar','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);
DB::table('filtros')->insert(['fregistro'=> '2021/02/15', 'nombre'=>'YACENIS PATRICIA BELTRAN MEJIA','cedula'=>'1019122164','telefono'=>'3207541203','correo'=>'MAIRINALANA01@GMAIL.COM','perfil'=>'Lider datos y metricas','campaña'=>'QNT','fuente'=>'rt','citadoE'=>'Citado Entrevista','noAplica'=>'','noInteresado'=>'','enviadoCapa'=>'','enviadoExm'=>'','PruebasE'=>'','yaTrabaja'=>'','numeroEqu'=>'','observacion'=>'','noAsiste'=>'','NoResponde2'=>'','YaNoInt'=>'','Estudiante'=>'','noAsisteEnt'=>'','entrevistaJefeInm'=>'','entrevistaGerencia'=>'','enviadocontratacion'=>'','entvOK'=>'','observacion2'=>'','usuario'=>'4,admin']);

    }
}

